# Use a Node image to build and run the application
FROM node:22-alpine

# Set the working directory
WORKDIR /app

# Copy package.json and install dependencies
COPY ./frontend/package.json  ./frontend/postcss.config.js  ./frontend/tailwind.config.js /app/

# Copy the source code
COPY ./frontend /app

RUN npm install
# Expose port
EXPOSE 5173

# Run the Vite development server
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
